In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from tools.data import DreemDatasets

In [2]:
use_datasets = ['eeg_1', 'eeg_2', 'eeg_3', 'eeg_4', 'eeg_5', 'eeg_6', 'eeg_7']


train_set, val_set = DreemDatasets('dataset/train.h5', 'dataset/train_y.csv', 
                                   split_train_val=0.8, seed=0, keep_datasets=use_datasets).get()

train_set.load_data("dataset/all_eegs/train") 

val_set.load_data("dataset/all_eegs/val")

train_set.close()  # Ne ferme que les fichiers h5. Si mis en mémoire, on a toujours accès aux données !
val_set.close()

Loading data in memory...
5412 in 7 datasets to load
Loading dataset eeg_1 ...
Loading dataset eeg_2 ...
Loading dataset eeg_3 ...
Loading dataset eeg_4 ...
Loading dataset eeg_5 ...
Loading dataset eeg_6 ...
Loading dataset eeg_7 ...
Done.
Loading data in memory...
1353 in 7 datasets to load
Loading dataset eeg_1 ...
Loading dataset eeg_2 ...
Loading dataset eeg_3 ...
Loading dataset eeg_4 ...
Loading dataset eeg_5 ...
Loading dataset eeg_6 ...
Loading dataset eeg_7 ...
Done.


In [3]:
clf = RandomForestClassifier(n_estimators=1000, random_state=0)

In [4]:
X, _, y = train_set[:]
X_val, _, y_val = val_set[:]

X = X.detach().numpy()
y = y.detach().numpy()
X_val = X_val.detach().numpy()
y_val = y_val.detach().numpy()

X = X.transpose((1, 0, 2))
X = X.reshape(-1, 7*1500)

X_val = X_val.reshape(-1, 7*1500)

In [5]:
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [6]:
y_pred = clf.predict(X_val)
print(accuracy_score(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

0.19881744271988175
[[ 99  58  26  41  28]
 [101  58  21  56  42]
 [109  56  24  37  36]
 [103  59  21  44  38]
 [105  69  32  46  44]]
